SIM ?= icarus
TOPLEVEL_LANG ?= verilog

PWD = $(shell pwd)
VERILOG_SOURCE = $(PWD)/../rtl/gemm_op.v

TOPLEVEL := gemm_op
MODULE   := tb_gemm_op

include $(shell cocotb-config --makefiles)/Makefile.sim